name: pull request
on:
  pull_request:
    types: [opened, synchronize]

env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: print
        run: ls packages/phoenix

      - name: install
        run: bun i
